name: Deploy to Production

on:
  workflow_dispatch:

concurrency:
  group: production_environment
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn
      - name: Build packages and apps
        run: yarn build
        env:
          BUILD_ENV: PRODUCTION
          NOCO_API_URL: ${{ secrets.NOCO_API_URL }}
          NOCO_AUTH_TOKEN: ${{ secrets.NOCO_AUTH_TOKEN }}
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          source: "build/*"
          target: ${{ secrets.REMOTE_TARGET }}
